### PR TITLE
Updated ruby icon

### PR DESCRIPTION
**Pull request by IevgenSobko**
Updated ruby icon for backward compatibility with awesome-fontconfig. It is the same code as used in Nerd font and have the same shape as you used previously(even little bit bigger so it will be clearer).

### Description

Thanks for contributing this Pull Request. Add a brief description of what this Pull Request does. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to support your changes.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of change :
  - [ ] New feature
  - [ ] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

### CODE REVIEW

**Comment by athityakumar** [comment]
@levgenSobko - Would it be possible to attach a screenshot of the new logo in the PR comment?

**Comment by IevgenSobko** [comment]
screenshot_20180403_142058

**Comment by athityakumar** [comment]
@levgenSobko - Ah, I meant a screenshot that with colorls. Just wanted to see how it looks with a set of other icons. Also, would it be possible to fix the (minor) Travis CI build error? 😄

**Comment by IevgenSobko** [comment]
@athityakumar 
Here is screenshot that you wanted
Old version at the top.
My updated version below.
screenshot_20180404_213206
Regarding Travis CI I don't have any experience with this CI system but will try to check was is going on.

**Comment by athityakumar** [comment]
Ah, the new Ruby icon looks bigger and more visible. Thanks for contributing! 😄 

Regarding the CI build error, the 1st line of `colorls.gemspec` file needs to be changed to `expand_path('lib', __dir__)` from `expand_path('../lib', __FILE__)`. This was nothing related to your changes, but it's just that Rubocop (linter) specifications have changed in between the master and your PR.

**Comment by IevgenSobko** [comment]
There is also new python icon in font-awesome-extended that included in nerd fonts. It has also bigger icon.

**Comment by athityakumar** [comment]
@levgenSobko - Feel free to add a new PR, or just keep pushing those changes to this PR. I'll merge this when you're ready. (Also, fix the Travis CI build error please) 😄

**Comment by athityakumar** [comment]
Ping @IevgenSobko  ^ 😃

**Comment by IevgenSobko** [comment]
@athityakumar I'll create another PR later. Currently to busy with job and personal issues

**Comment by IevgenSobko** [comment]
Hello @avdv . My intention was to have bigger icons that aligned with folders. Original one is somewhat smaller than for instance folder icon. 
I have experienced this behavior with just half of icon displayed.
It depends on terminal and symbol representation. For instance at the following screenshot you can see that command line prompt has such issue in Konsole terminal.

**Pull request closed without merging**
