### PR TITLE
Only filter hidden files when listing a directory

### LINKED ISSUE #101: always list hidden files when given as arguments explicitly
Currently, colorls does not support listing hidden files, even when given explicitly as an argument:

```
$ colorls .bashrc

   Nothing to show here
```

It should only skip hidden files when listing directories and `-a` or `-A` is not in effect.

### LINKED ISSUE #104: Long information not shown for files given as argument
colorls just does not find the given file to show the extended information:

```
$ ls ~/.bashrc -l -a

"does not exist: /home/claudio/.bashrc//home/claudio/.bashrc"
  [No Info]                                           /home/claudio/.bashrc
```

Note the second line which is caused by a `p` statement I have added to the `long_info` method. It shows that for the given argument it erroneously constructs a non-existing path.

### PR DESCRIPTION
**Pull request by avdv**
Fixes #101 and fixes #104.

### CODE REVIEW

**Comment by athityakumar** [comment]
@avdv - Thanks for contributing. This looks good, can you also add a sample fixture file and command testing it to `.travis.yml` file?

**Comment by avdv** [comment]
> @avdv - Thanks for contributing. This looks good, can you also add a sample fixture file and command testing it to .travis.yml file?

Done, hope it is what you had in mind. :smile:

**Comment by athityakumar** [comment]
Hmm, wouldn't just `colorls spec/fixtures/.hidden-file` do into `.travis.yml`? If we're going to test for equality of the output, feel free to add a test in a `spec/core_spec.rb` file. :smile:

**Comment by avdv** [comment]
> Hmm, wouldn't just colorls spec/fixtures/.hidden-file do into .travis.yml?

No, since the bug manifests itself only when listing a hidden file in the current directory.

> If we're going to test for equality of the output, feel free to add a test in a spec/core_spec.rb file.

You mean that I should add that file? Or did you mean `spec/colorls_spec.rb`?

**Comment by athityakumar** [comment]
@avdv - It'd be better to have it in `spec/core_spec.rb`. In future, all tag functionalities can be tested in this file.

**Comment by athityakumar** [comment]
@avdv - Yes, that works. Please add the rspec test and we're ready to merge.

**Comment by avdv** [comment]
I was AFK over the weekend...

But now, I made the changes you requested to the last commit.

**Pull request merged**
