### PR TITLE
removed bug of ignored files

### PR DESCRIPTION
**Pull request by rohitner**
- Relevant Issues : #156 
- Relevant PRs : (none)
- Type of change :
  - [x] New feature
  - [x] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

### CODE REVIEW

**Comment by athityakumar** [comment]
Hey @rohitner! This fix works well for ignored files and completely ignored directories. But for partial ignores, it skips showing any status. For example, look at the below screenshot. The `.DS_Store` is ignored at the `lib/` and `exe/` directories, and they do contain other added files. Can we have them shown as tick (for all files in them that have been committed) rather than an empty space?

image

**Comment by rohitner** [comment]
Is it okay to show some other sign if not blank for dirs which have ignored files?

**Comment by athityakumar** [comment]
Nope. IMO, I think there should be a preference between the status shown for directories.

1. Deleted and Modified have the same preference
2. Added has lesser preference
3. Ignored has a much lesser preference.

**Comment by rohitner** [comment]
There are issues regarding showing completely ignored files since git anyway ignores empty files and looks only for change in content. However showing ignored files works well.

**Comment by athityakumar** [comment]
Hmm, can you try based on something like this?

```ruby
class Dir
  def self.deep_entries(path)
    (self.entries(path) - ['.', '..']).map do |entry|
      if Dir.exist?("#{path}/#{entry}")
        self.deep_entries("#{path}/#{entry}")
      else
        entry
      end
    end.flatten
  end
end

def git_dir_info(path)
  ignored = @git_status.select { |file, mode| file.start_with?(path) && mode==' ' }.keys
  present = Dir.deep_entries(path).map { |p| "#{path}/#{p}"}
  return '    ' if (present-ignored).empty?

  modes = (added-ignored).map { |file| @git_status[file] }.select { |mode| !mode.nil? }
  # modes = @git_status.select { |file, _mode| file.start_with?(path) }.values
  return '  ✓ '.colorize(@colors[:unchanged]) if modes.empty?
  Git.colored_status_symbols(modes.join.uniq, @colors)
end
```

We're having a problem with showing status of dirs that are partially gitignored and partially committed/modified right? So, let's check recursively for the file of the directory whether there are any such added/modified/deleted files. What say?

**Comment by rohitner** [comment]
That indeed works! :clinking_glasses: .This is quite similar to my approach, but I messed up in writing the recursion :sweat_smile: .

**Pull request merged**
