### PR TITLE
Support -A | --almost-all flag and Fix -a | --all flag

### LINKED ISSUE #57: Support -A / --almost-all
From `man ls`:
image

### Expected behaviour
1. `colorls -A` list all entries except `.` and `..`
2. `colorls -a` list all entries including `.` and `..`

### Current behaviour
1. There's no `-A` nor `--almost-all`
2. Option `-a`/`--all` is doing `-A`/`--almost-all`'s jobs

### PR DESCRIPTION
**Pull request by adimasuhid**
### Changes

- [x] Added support for -A flag
- [x] Fixed -a flag

Closes #57 and #39

### CODE REVIEW

**Comment by athityakumar** [comment]
@adimasuhid - Thanks for working on this. 😄 

How about adding tests for flags later? For now, just add the `colorls -A` to the `travis.yml` file and remove the spec (and fixtures) for the `-A` flag.

**Comment by adimasuhid** [comment]
@athityakumar Sure will do. Though do you mean add specs in a separate PR or just remove specs all together?

**Comment by athityakumar** [comment]
@adimasuhid - I'd like it for specs to be added, provided specs for all flags are added. Else, it becomes too inconsistent. Hence,

- For this PR, revert the spec part. Add the Travis config.
- If you don't mind adding spec for all flag options usage (as currently done in travis.yml), please do it in a different PR. Else, no issues. We can make do with Travis build log reports as of now for reviewing PRs.

**Comment by adimasuhid** [comment]
@athityakumar That makes sense thanks. Will do. I'll try to add specs for all if I have time though that's probably just the happy path for the mean time.

**Comment by adimasuhid** [comment]
@athityakumar Updated as suggested. 

Out of context question though: How can you reply so fast, any time of the day? haha

**Comment by athityakumar** [comment]
@adimasuhid - Haha. Purely a matter of coincidence that I'm awake at that time. 😄

**Pull request merged**
