### PR TITLE
add '-L' option

### PR DESCRIPTION
**Pull request by t-mangoe**
### Description

Thanks for contributing this Pull Request. Add a brief description of what this Pull Request does. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to support your changes.

I added `-H` option.
This PR closes the #515 issue.

- Relevant Issues : #515 
- Relevant PRs : (none)
- Type of change :
  - [x] New feature
  - [ ] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

### CODE REVIEW

**Comment by errantepiphany** [comment]
Would love to see this get merged! :)

**Review by avdv — CHANGES_REQUESTED** [review]
Hi.

IMO, this does not  implement the `-H` option, actually it implements the `-L` option:
> `-L`, `--dereference`
>              when  showing  file information for a symbolic link, show information for the file the link references rather than for the link itself

Could you change the option and help text accordingly, please?!

**Comment by t-mangoe** [comment]
@avdv
Thank you for comment!
I have changed the option name. Is it necessary to change the help text?

**Review by avdv — APPROVED** [review]
The help text is actually fine, thank you @t-mangoe!

**Pull request merged**
