### PR TITLE
Fixed date not showing if file is older than 1 hour

### PR DESCRIPTION
**Pull request by Metamist**
Before:

After:

### CODE REVIEW

**Comment by Metamist** [comment]
Looks like it was already fixed literally 5 minutes before this PR. disregard this!

**Comment by athityakumar** [comment]
@Metamist - Ah, sorry. There were some bugs that I had overlooked while merging PR #119 - had to fix them ASAP for convenience of contributors. 😄

**Comment by Metamist** [comment]
@athityakumar No problem!

**Comment by Metamist** [comment]
I feel like the fixes on the master branch are still incorrect though.
Master:


This PR:

**Pull request merged**
