### PR TITLE
add symlink display for -l

### PR DESCRIPTION
**Pull request by GladOSkar**
According to Discussion on #35

I decided to it the way `ls` does it: show symlinks by default with `-l`. I think that is more suitable here.

Let me know if that doesn't work for you

### CODE REVIEW

**Comment by GladOSkar** [comment]
Wait, it still has bugs

**Comment by athityakumar** [comment]
@GladOSkar - We could probably have a symlinked file at `spec/fixtures/` and add it to `travis.yml` with `colorls -l spec/support`. 😄

**Comment by GladOSkar** [comment]
@athityakumar sure

**Comment by GladOSkar** [comment]
OK so i had to do a lot of fixes. Reading symlinks is apparently dangerous since they may be dead, and in that case you can't read any info from them of course. So i added some detection for them.

Also, in row 146 i changed `6*` to `7*` since that apparently hadn't been updated after adding the slashes behind folders and led to broken chunking at some terminal widths.

**Comment by adimasuhid** [comment]
@GladOSkar This is nice. I'm thinking maybe we should put the sample files inside a dir in `spec/fixtures`, something like `spec/fixtures/symlinks`. This is to ensure that the files inside the dir is specifically related to the part being tested (symlinks). And also because I think `spec/support` is more for rspec helpers (or is just a rails convention?).

Let me know what you think @GladOSkar @athityakumar

**Comment by adimasuhid** [comment]
Awesome good to know. Thanks :+1:

**Comment by GladOSkar** [comment]
Done

**Pull request merged**
