### PR TITLE
Add Checking of YAML file order

### LINKED ISSUE #8: Check for order of data in YAML files
Both `aliases.yaml` and `formats.yaml` have a certain order, in which data should be inserted. Both YAML files are key-value hashes, with - 

- `aliases.yaml` : The values are sorted alphabetically. For each set of keys mapping to a value, those set of keys are also sorted alphabetically.
- `formats.yaml` : The keys are sorted alphabetically.

It'd be good to have a (Ruby?) script that automatically checks for this order, and use with Travis CI to decide when PRs are submitted.

### PR DESCRIPTION
**Pull request by adimasuhid**
Things that we're done in this PR:
- [x] Added Ruby script to check simple yaml (key - value) of their correct order as specified in #8 
- [x] Added script running to Travis
- [x] Arranged some yaml to be on the correct alphabetical order

Script details:
- You can run the script thru calling ruby via bash: `ruby yaml_sort_checker.rb filename.yaml`
- It has an option `-v` or `--by-value` to sort alphabetically by value (and the keys of those values)
- When the yaml is not sorted correctly, it raises a `YamlSortChecker::NotSortedError` together with the array that is not sorted
- Even though it has specs upon creation, decided not to add it yet since it is not really the core of the tool

Closes #8 

Let me know how I can improve this. Thanks!

### CODE REVIEW

**Comment by athityakumar** [comment]
@adimasuhid - Thanks for contributing! This script checks well for whether the data in the YAML files are in proper order, but I feel the output could be more clear regarding exactly what keys in the yaml file are not in order.

That is, even if one key is misplaced it says that the whole array of keys is misplaced. Though technically correct, it'd be better to include a diff checker rather than order-matching in such cases IMO. We can use the [diffy gem](https://github.com/samg/diffy) to get the Diff between the sorted values and values read from the YAML file.

**Comment by adimasuhid** [comment]
@athityakumar Ooh nice, that could work. Although I find the part where we'd have to sort the keys per value (for `aliases.yaml`) a bit tricky, which is why I resorted to arrays. What do you think would be a better way to go about there?

The other solution I'm thinking is, we go with the arrays, and then when it raises an error, we convert the arrays (sorted and unsorted) to a multi-level string that we could diff. For keys and values sorting, that would be straightforward. However for sorting keys per value, it would display only the current value being checked. Something like:

```
# apple in file_aliases.yaml
-localized
ds_store
+localized
```

What do you think?

**Comment by athityakumar** [comment]
@adimasuhid - How about checking diff between strings?

```ruby
require 'diffy'

def hash_to_str(hash)
  hash.to_a.map { |x| x.join(' ') }.join("\n")
end

actual_hash   = YAML.safe_load('/path/to/yaml/file')
expected_hash = sorted_hash # Computed by your module
actual_str    = hash_to_str(actual_hash)
expected_str  = hash_to_str(expected_hash)

puts Diffy::Diff.new(expected_str, actual_str)
```

**Comment by athityakumar** [comment]
@adimasuhid - BTW, let's have this as specs itself. I'm developing on the ruby gem from script for colorls, in the `ruby-gem` branch. Inform me if you'd like to make the changes wrt that branch (gem), or with wrt current master (ruby script). 😄

**Comment by athityakumar** [comment]
Ping @adimasuhid 

Update : Colorls has now become a Ruby gem. Please make your script into a spec file, resolve merge conflicts and it can be merged. 😄

**Comment by adimasuhid** [comment]
hi @athityakumar that's cool thanks. I'll try to work on it later today so that we could merge it. If not probably the weekend. Cheers!

**Comment by adimasuhid** [comment]
@athityakumar Sorry was only able to update today. Updated the script as suggested:
- Move checks into rspec
- Display error as diffs in hash

Let me know if this is good. Thanks!

**Comment by athityakumar** [comment]
Great work, @adimasuhid 🎉 👍 

Though the specs can definitely be cleaned up, I think this PR is enough to get merged. But, feel free to clean the specs if you'd like to, in a different PR. 😄

**Pull request merged**
