### PR TITLE
Add a changlog file

### LINKED ISSUE #49: Add CHANGELOG.md
It's quite important to document the changes that were made in each version of the released gem.

### PR DESCRIPTION
**Pull request by igordcsouza**
Adding a change log file CLOSE #49

### CODE REVIEW

**Comment by athityakumar** [comment]
Hey, thanks for contributing. The changelog file should also contain major and minor changes introduced by each version.

**Comment by athityakumar** [comment]
Ping @igordcsouza

**Comment by igordcsouza** [comment]
Hey, i was in some days off. I will look at this tomorrow.

**Comment by athityakumar** [comment]
Ping @igordcsouza - v1.0.1 has been released and the version tags will be tagged to corresponding commits from now onwards. But changelog until v0.7.0 would have to be added manually. 😄

**Comment by athityakumar** [comment]
@igordcsouza - To make things simpler, you could use the diff between these commits to create the changelog. 

https://github.com/search?l=&q=Updates+v0+repo%3Aathityakumar%2Fcolorls+user%3Aathityakumar&ref=advsearch&type=Commits&utf8=%E2%9C%93

**Comment by athityakumar** [comment]
An even easier way of tracing back the changes would be to look into the history of the `version.rb` file : https://github.com/athityakumar/colorls/commits/master/lib/colorls/version.rb 😄

**Comment by athityakumar** [comment]
Closing this PR due to no response/activity. Feel free to open a new PR if you're interested. 😄

**Pull request closed without merging**
